/**
 * Scheduled-transaction store — Phase 8.
 *
 * Real CRUD over the encrypted `scheduledTransactions` repository, plus the
 * run/due machinery that materialises recurring transactions:
 *
 * - `initialize(repos)` / `load` / `add` / `update` / `remove` / `reset` mirror
 *   the other domain stores (encrypted table, in-memory `items` projection).
 * - `processDue(asOf = today)` runs the pure `runDueSchedules` over the loaded
 *   schedules: persists each generated AUTO transaction (via
 *   `useTransactionStore.getState().add`), writes the advanced schedules back
 *   to the encrypted table, refreshes `items`, and exposes the due MANUAL
 *   schedules on `pendingManual` for the UI to render with a "Post" button.
 * - `postManual(scheduleId)` generates + advances a single MANUAL schedule on
 *   demand: it persists the transaction, writes the advanced schedule back,
 *   and drops it from `pendingManual`.
 *
 * The store is the ONLY seam between the pure scheduling core and the rest of
 * the app; it owns persistence side-effects so the core stays side-effect-free
 * and trivially testable.
 */
import { create } from 'zustand';

import type { EncryptedTable } from '@/lib/crypto';
import type { Repositories, ScheduledTransaction, Transaction } from '@/lib/db';
import {
  advanceSchedule,
  generateFromSchedule,
  runDueSchedules,
} from '@/lib/scheduling';

import { useTransactionStore } from './transactionStore';

export interface ScheduledStoreState {
  /** In-memory projection of the encrypted table; empty until `initialize`. */
  items: ScheduledTransaction[];
  /** Due MANUAL schedules surfaced by the last `processDue` run. */
  pendingManual: ScheduledTransaction[];
  /** Transactions generated by the last `processDue` run (for UI feedback). */
  lastGenerated: { scheduleId: string; transaction: Transaction }[];
  /** Injected at unlock; null before the user authenticates. */
  repos: Repositories | null;
  /** Bind the store to its repository and load the initial list. */
  initialize: (repos: Repositories) => Promise<void>;
  /** Re-read every row from the encrypted table into `items`. */
  load: () => Promise<void>;
  /** Add a new schedule (caller sets `id` to a fresh UUID). */
  add: (item: ScheduledTransaction) => Promise<void>;
  /** Merge a patch into the stored schedule and refresh. */
  update: (id: string, patch: Partial<ScheduledTransaction>) => Promise<void>;
  /** Delete a schedule by id and refresh. */
  remove: (id: string) => Promise<void>;
  /** Detach from the repository and clear the in-memory list (logout). */
  reset: () => void;
  /**
   * Run every loaded schedule against `asOf` (defaults to today's ISO date).
   * Persists each generated AUTO transaction via the transaction store, writes
   * the advanced schedules back to the encrypted table, refreshes `items`,
   * and stores the due MANUAL schedules on `pendingManual`. Returns the
   * generated transactions for the caller to display.
   */
  processDue: (asOf?: string) => Promise<{
    generated: { scheduleId: string; transaction: Transaction }[];
    pendingManual: ScheduledTransaction[];
  }>;
  /**
   * Generate + advance a single MANUAL schedule on demand: persist its
   * transaction, write the advanced schedule back, and drop it from
   * `pendingManual`. Returns the generated transaction, or `undefined` if the
   * schedule is absent or not in `pendingManual`.
   */
  postManual: (scheduleId: string) => Promise<Transaction | undefined>;
}

function select(repos: Repositories): EncryptedTable<ScheduledTransaction> {
  return repos.scheduledTransactions;
}

function notInit(): Error {
  return new Error(
    'scheduled store not initialized — call initializeStores(repos) at unlock',
  );
}

/** Today's ISO `YYYY-MM-DD` in the host's local time zone. */
function todayIso(): string {
  const d = new Date();
  const m = String(d.getMonth() + 1).padStart(2, '0');
  return `${d.getFullYear()}-${m}-${String(d.getDate()).padStart(2, '0')}`;
}

export const useScheduledStore = create<ScheduledStoreState>((set, get) => ({
  items: [],
  pendingManual: [],
  lastGenerated: [],
  repos: null,

  initialize: async (repos) => {
    set({ repos });
    await get().load();
  },

  load: async () => {
    const { repos } = get();
    if (!repos) return;
    set({ items: await select(repos).toArray() });
  },

  add: async (item) => {
    const { repos } = get();
    if (!repos) throw notInit();
    await select(repos).add(item);
    await get().load();
  },

  update: async (id, patch) => {
    const { repos } = get();
    if (!repos) throw notInit();
    const table = select(repos);
    const existing = await table.get(id);
    if (!existing) throw new Error(`schedule ${id} not found`);
    await table.put({ ...existing, ...patch, id });
    await get().load();
  },

  remove: async (id) => {
    const { repos } = get();
    if (!repos) throw notInit();
    await select(repos).delete(id);
    await get().load();
  },

  reset: () =>
    set({ items: [], pendingManual: [], lastGenerated: [], repos: null }),

  processDue: async (asOf) => {
    const { repos, items } = get();
    if (!repos) throw notInit();
    const due = asOf ?? todayIso();
    const { generated, updatedSchedules, pendingManual } = runDueSchedules(
      items,
      due,
    );

    // Persist each generated AUTO transaction via the transaction store so the
    // transaction list + balances refresh in lockstep. The transaction store
    // validates splits (templates carry none here) and reloads its projection.
    for (const g of generated) {
      await useTransactionStore.getState().add(g.transaction);
    }

    // Write the advanced/unchanged schedules back. We `put` every schedule in
    // `updatedSchedules` whose nextDate changed (the AUTO due ones); the pure
    // core returns the same object identity for non-due + manual schedules,
    // but re-putting them is a harmless no-op and keeps the loop simple.
    for (const s of updatedSchedules) {
      await select(repos).put(s);
    }

    set({ items: updatedSchedules, pendingManual, lastGenerated: generated });
    return { generated, pendingManual };
  },

  postManual: async (scheduleId) => {
    const { repos, pendingManual } = get();
    if (!repos) throw notInit();
    const idx = pendingManual.findIndex((s) => s.id === scheduleId);
    if (idx === -1) return undefined;
    const s = pendingManual[idx];

    // Generate the transaction dated at the schedule's nextDate, persist it,
    // advance the schedule by one period, and write both back.
    const tx = generateFromSchedule(s);
    await useTransactionStore.getState().add(tx);

    const advanced = advanceSchedule(s);
    await select(repos).put(advanced);

    const nextPending = pendingManual.filter((p) => p.id !== scheduleId);
    // Refresh `items` from the table so the advanced schedule is reflected
    // consistently (it may also have been changed by `processDue` above).
    await get().load();
    set({ pendingManual: nextPending });
    return tx;
  },
}));
